### ISSUE TITLE
Versions below 5.81 are deprecated

### ISSUE THREAD

**Issue by Arsikkk98** [Innim/flutter_login_vk#12]
Error: Invalid request: versions below 5.81 are deprecated. Version param should be passed as \"v\". \"version\" param is invalid and not supported.

Tell me how to change the version?

**Comment by greymag** [comment]
Hey. Update to the last version of the package. There is no "version" param in our implementation, we just use default one.

**Comment by Arsikkk98** [comment]
@greymag thank you for a quick reply. I already had a version 2.0.0+1, and this was a problem on the server.
However, now I know that version cannot be set.
