### ISSUE TITLE
Bump vk sdk version for Android

### ISSUE THREAD

**Issue by sanekyy** [Innim/flutter_login_vk#16]
Hi.
VK SDK version for Android now is 3.4.0.

Your plugin use 3.2.2. Bump it please:)

**Comment by greymag** [comment]
Hey!

Is any helpful changes in this new version?

VK changed the SDK api (again) and make it worse (again). Also I can't find changelog, if you have - please share a link. So update to this new version takes some time.

**Comment by greymag** [comment]
Updated VK SDK version to 3.5.0 in [v2.2.0](https://pub.dev/packages/flutter_login_vk/versions/2.2.0)
