### ISSUE TITLE
sdk_fingerprint is not initialized

### ISSUE THREAD

**Issue by k0lourful** [Innim/flutter_login_vk#20]
Making an android app, everything's done according to readme and it's not working on any device, except the emulator. I uploaded both app's debug and release sha1 fingerprints, and one from Google Play Console. And here's the result on ios:
<details>
<summary>Safari screenshot</summary>

![image](https://user-images.githubusercontent.com/41012295/148691197-3977a1bf-f327-4f2f-9c1f-810e97915515.png)

</details>

**Comment by greymag** [comment]
Hey! It's not about fingerprint (it's iOS, but fingerprints you took from Google Play is for Android), it's about URL schemes. See [iOS section in README](https://github.com/Innim/flutter_login_vk#ios).

**Comment by k0lourful** [comment]
Still I can't get it working on Android. For more details, here's the res/strings.xml contents:
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">APP</string>
    <string name="facebook_app_id">something</string>
    <string name="fb_login_protocol_scheme">something</string>
    <integer name="com_vk_sdk_AppId">??????</integer>
</resources>
```

AndroidManifest.xml has the following under application tag:
```
<activity
            android:name="com.vk.sdk.VKServiceActivity"
            android:label="ServiceActivity"
            android:theme="@style/VK.Transparent" />
```
As well as internet permission.

And here're the fingerprints in vk console. Tried inserting with and without colons. The vk appid matches the one in strings.xml.
![image](https://user-images.githubusercontent.com/41012295/148773595-205a9d33-85a7-4f66-996a-a39138163c42.png)

**Comment by greymag** [comment]
Hashes should be without colons, like this: ![](https://d.pr/i/nwgbdT+)

Is `com_vk_sdk_AppId` in `res/strings.xml` set? What error do you have?

**Comment by k0lourful** [comment]
Done. Still nothing.

> Is `com_vk_sdk_AppId` in `res/strings.xml` set? What error do you have?

Yes, I covered it in my example by question marks, it's just 6 digits. And the error:
![image](https://user-images.githubusercontent.com/41012295/148780274-f7732aa6-28a6-4f78-9f9e-f03b741ec60b.png)

**Comment by k0lourful** [comment]
False alarm. The release fingerprint was missing.
