### ISSUE TITLE
Ошибка при билде для iOS

### ISSUE THREAD

**Issue by FeofanGreek** [Innim/flutter_login_vk#28]
ВОзникает ошибочка при сборке под ИОС

[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `flutter_login_vk` depends upon `VK-ios-sdk`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

 что может помочь?

**Comment by greymag** [comment]
Добрый день. Пропустил issue. А у вас нет `use_modular_headers!` в `ios/Podfile`?

**Comment by greymag** [comment]
Нет ответа, так что пока закрываю issue. Если проблема все еще актуальна, пожалуйста, откройте снова.
