### ISSUE TITLE
Как можно получить Пол и День рождения пользователя?

### ISSUE THREAD

**Issue by Rudentsov** [Innim/flutter_login_vk#30]
Добрый день!
Не получается с помощью плагина получить Пол и День рождения.

В VKScope отсутствуют нужные перечисления.
С помощью customScope также не получилось это сделать:
final res = await vk.logIn(scope: [VKScope.email], customScope: ['sex', 'bdate']);

Остаётся вариант - после авторизации получать дополнительным запросом вручную с помощью http.get и token.
Но это означает дополнительный запрос.
Может быть, есть другие варианты?

**Comment by greymag** [comment]
Добрый день. Вы правильно написали - подразумевается что дополнительные данные вы будете загружать отдельным запросом. Цель плагина предоставить доступ к базовой информации о профиле, которая нужна именно для входа. Более глубокую интеграцию с ВК вам нужно реализовывать самостоятельно.
