### ISSUE TITLE
Можно ли вызывать окно согласия как виджет?

### ISSUE THREAD

**Issue by Rudentsov** [Innim/flutter_login_vk#31]
Можно ли вызывать окно согласия в плагине как виджет?
Вот этот метод, имею в виду:
final res = await vk.logIn();

Наподобие того, как сделано в google_sign_in
Там окно согласия показывается во сплывающем виджете (типа AlertDialog), что очень удобно.

Дело в том, что иногда при показе окна согласия/авторизации VK, вырубает приложение, видимо памяти не хватает, после чего приходится заново запускать приложение, пока не добьёшься, чтобы приложение не вырубилось.

**Comment by greymag** [comment]
Тут мы сами не показываем Activity, это делает VK SDK, поэтому такой возможности нет
