### ISSUE TITLE
Empty vk.oauth.com page after giving the access

### ISSUE THREAD

**Issue by darkstarx** [Innim/flutter_login_vk#36]
Initialize the plugin - ok
```dart
      final result = await _plugin.initSdk(scope: [ VKScope.email ]);
      if (result.isValue) {
        if (result.asValue?.value == true) {
          _initialized = true;
        } else {
          _log.warning('Failed to init SDK');
        }
      } else {
        final error = result.isError
          ? result.asError?.error
          : null;
        _initialized = false;
        _log.warning('Failed to init SDK: $error');
      }
```

Signing in - stuck
```dart
    final loginResult = await _plugin.logIn(scope: [ VKScope.email ]);
    if (loginResult.isError) {
      final error = loginResult.asError?.error;
      _log.warning('Failed to log in the VK: $error');
    } else if (loginResult.isValue) {
      if (loginResult.asValue?.value.isCanceled ?? false) {
        _log.warning('Failed to log in the VK: cancelled');
      }
    }
```
It asks the access
![Simulator Screen Shot - iPhone 8 - 2022-11-25 at 12 43 09](https://user-images.githubusercontent.com/3534966/203952100-fc221877-f07a-416b-a949-ee4c31b4defd.png)

after that it loads the blank page and that's it.
![Simulator Screen Shot - iPhone 8 - 2022-11-25 at 12 43 24](https://user-images.githubusercontent.com/3534966/203952333-788e5b2e-80c3-47b8-8bf5-43128e103f40.png)

If I tap the `Done` button, it returns cancelled result in the code.

flutter_login_vk: ^2.2.1+1

**Comment by greymag** [comment]
Hello. Please check following:

1) Your application has been configured as described in [README](https://github.com/Innim/flutter_login_vk#ios). Pay attention to `CFBundleURLTypes` parameter.
2) If configuration is fine then you should check your `ios/Runner/AppDelegate.swift` to make sure that no-one intercept intent handling in `application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool`. You can post file content here and I'll help you with that.
3) Also you should check any other plugins that can intercept this handling.

**Comment by darkstarx** [comment]
OMG yeah, my bad. There was some code in the `OpenURLOptionsKey` which broke the intent handling. Now it works fine, thanks a lot!
