### ISSUE TITLE
Код с ошибками в инструкции

### ISSUE THREAD

**Issue by rednikisfun** [Innim/flutter_login_vk#38]
В Readme на pub.get указана инструкция по использованию плагина, но при использовании данного кода выявляется несколько ошибок:

`final VKAccessToken accessToken = res.accessToken;`

1. В данной строчке ошибка заключается в том что для `res` не существует геттера `accessToken`, скорее всего было изменено на следующее:

```
final VKAccessToken? accessToken = data.accessToken;
print('Access token: ${accessToken?.token}');
```

2. В данной части кода указана попытка использовать методы `getUserProfile` и `getUserEmail` обращаясь к переменно `fb`, тогда как такая переменная не была объявлена:

```
final profile = await fb.getUserProfile();
final email = await fb.getUserEmail();
```

Скорее всего имелось ввиду:

```
final profile = await vk.getUserProfile();
final email = await vk.getUserEmail();
```

3. В попытке распечатать данные пользователя используется следующий код:

`print('Hello, ${profile.firstName}! You ID: ${profile.userId}');`

Однако profile не содержит таких геттеров как firstName и userId

Скорее всего стоит использовать:

```
print('Hello, ${profile.asValue!.value!.firstName}! You ID: ${profile.asValue!.value!.userId}');
```

**Comment by greymag** [comment]
Да уж, в примере в README просто ужас 🤦  Спасибо что указали! Поправил.
