### ISSUE TITLE
sdk fingerprint is incorrect 

### ISSUE THREAD

**Issue by aytoku** [Innim/flutter_login_vk#39]
почему-то выдает ошибку "sdk fingerprint is incorrect ", когда пытаюсь авторизоваться через вк
делал все по гайду, создал приложение, заполнил поля "Отпечаток сертификата для Android", "Название пакета для Android", "Main activity для Android"
в отпечатке указал sha1, sha256
в названии пакета указал название из android manifest
в Main activity для Android <название пакета>.MainActivity
в плане кода тоже все по гайду, указал айди приложения, добавил proguard-rules.pro, прописал в strings айди приложения, в MainActivity добавил activity для вк
подскажите почему может быть такая ошибка?

**Comment by aytoku** [comment]
sha ключи нужно вводить без пробелов

**Comment by ag0196** [comment]
@aytoku в смысле без пробелов? Там же всё через двоеточие, и для каждого ключа можно отдельное поле создать в настройках ведь, или я что-то не там смотрю? А то такая же ошибка, всё SHA-1 ключи которые введены в Firebase и дают приложению работать без перебоев перевёл в VK, всё равно ошибка

**Comment by greymag** [comment]
Именно двоеточия (и префикс `SHA1: `) и надо удалить, как указано в [документации](https://vk.com/dev.php?method=android_sdk&f=1.1.%20Certificate%20Fingerprint):

> Удалив все двоеточия, Вы получите отпечаток своего ключа.
