### ISSUE TITLE
Api Code 101

### ISSUE THREAD

**Issue by eugeen3** [Innim/flutter_login_vk#7]
I began to use VK login plugin about 2 months ago and all goes well from the start. But at the last time it sometimes throws exception `[VK] Get profile error: PlatformException(API_ERROR, Get profile error: null, {apiCode: -101, message: null}, null)
`. Documentation https://vk.com/dev/errors says this number signals about wrong API_IP (application identifier) in VK application settings. But i've never changed it neither in my Flutter app nor in VK application. What can cause the problem?

**Comment by greymag** [comment]
Hey! What version of the package do you use? If it's =>2.0.0 make sure that you've added application id in `string.xml`/`Info.plist`, like described in [README](https://github.com/Innim/flutter_login_vk#android). This is breaking changes in new version.

**Comment by eugeen3** [comment]
I used 1.0.0 version. Now I've upgraded it ti 2.0.0+1 and got this: `[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: 'package:flutter_login_vk/src/vk_login.dart': Failed assertion: line 38 pos 12: '_initialized': SDK is not initialized. You should call initSdk() first`. Here is my code: 
```
class VKSignInApi {
  String _sdkVersion;
  VKAccessToken _token;
  VKUserProfile _profile;
  String _email;
  bool _sdkInitialized = false;
  final plugin = VKLogin(debug: true);

  void logout() async {
    await plugin.logOut();
  }

  Future<List> login() async {
    await _initSdk();
    await _getSdkVersion();
    await _updateLoginInfo();

    final res = await plugin.logIn(scope: [
      VKScope.email,
    ]);

    if (res.isValue) {
      final VKLoginResult data = res.asValue.value;
      List vkData = [_profile, _token];
      if (!data.isCanceled) {
        return vkData;
      } else {
        return null;
      }
    }
  }

  Future<void> _initSdk() async {
    await plugin.initSdk();
    _sdkInitialized = true;
    await _updateLoginInfo();
  }

  Future<void> _getSdkVersion() async {
    final sdkVersion = await plugin.sdkVersion;

    _sdkVersion = sdkVersion;
  }

  Future<void> _updateLoginInfo() async {
    if (!_sdkInitialized) return;

    final _plugin = plugin;
    final token = await _plugin.accessToken;
    final profileRes = token != null ? await _plugin.getUserProfile() : null;
    final email = token != null ? await _plugin.getUserEmail() : null;

    _token = token;
    _profile = profileRes?.asValue?.value;
    _email = email;
  }
}
```

**Comment by greymag** [comment]
Please, provide full stack trace for error.

**Comment by greymag** [comment]
Pay attention on first line: 
```flutter: [VK] Init SDK error: PlatformException(INVALID_ARGS, App ID is not found. Please add VKAppId parameter in Info.plist, null, null)```

You didn't add application id as required. You should add application id in string.xml/Info.plist - see [README](https://github.com/Innim/flutter_login_vk) for details.

**Comment by eugeen3** [comment]
It says it can't VKAppId in Info.plist, but i have two Info.plist files (Info-Debug.plist and Info-Release.plist). I've had to make two copies of this file to fix one critical bug. Both of this files contains VKAppId.

**Comment by eugeen3** [comment]
I tried to run example app with my VKAppId and faced "Safari cannot open page because the address is invalid" dialog on webview page.

**Comment by greymag** [comment]
Looks like you didn't replace id in `CFBundleURLSchemes`

**Comment by greymag** [comment]
No answer, so I believe the problem is solved.
