### ISSUE TITLE
No open windows login

### ISSUE THREAD

**Issue by Taverz** [Innim/flutter_login_vk#8]
when you click on the login button, it gives an error. **{"error" : "invalidate_request", "error_descrition":"incorrect app. Unavialable for apps with direct auth."}**

**Comment by greymag** [comment]
Hey! What version of the package do you use? If it's =>2.0.0 make sure that you've added application id in `string.xml`/`Info.plist`, like described in [README](https://github.com/Innim/flutter_login_vk#android)

**Comment by Taverz** [comment]
made sure I have it in the code. Even your example does not start for me

**Comment by greymag** [comment]
You should update to the `^2.0.0`. Unfortunately VK deprecate old version SDK and now we need to define application id in resources instead if dart code.

**Comment by greymag** [comment]
@Taverz does upgrade solve problem?

**Comment by greymag** [comment]
No answer, so I'm closing the issue
